syntax = "proto3";
package item;
option go_package = "github.com/KolesnikDmitriy/item/api;item";

import "google/api/annotations.proto";

service Item {
    rpc GetItem(GetItemRequest) returns (GetItemResponse) {
        option (google.api.http) = {
            get: "/v1/item/{id}"
        };
    };
    rpc PostItem(PostItemRequest) returns (PostItemResponse) {
        option (google.api.http) = {
            post: "/v1/item"
            body: "*"
        };
    };
}

message GetItemRequest{
    int64 id = 1;
}

message GetItemResponse{
    string title = 1;
    string description = 2;
}

message PostItemRequest{
    string title = 1;
    string description = 2;
}

message PostItemResponse{
    int64 id = 1;
}